image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [864.32188,   0.     , 635.55623,
           0.     , 864.71411, 484.35412,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.102473, 0.086980, -0.000091, 0.000224, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [849.03014,   0.     , 636.1922 ,   0.     ,
           0.     , 848.34767, 485.3291 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
